# Reads a file from a predefined path in the workspace git PipelineResource
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-stuff-file-exists
spec:
  params:
  - name: args
    type: array
  resources:
    inputs:
    - name: workspace
      type: git
      targetPath: newworkspace
  steps:
  - name: read
    image: ubuntu
    command: ["/bin/bash"]
    args: ['$(inputs.params.args[*])']  # tests that new targetpath and previous task output is dumped
